# Generated by Django 5.2.7 on 2025-11-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jins')),
                ('color', models.CharField(max_length=100, verbose_name='Rang')),
                ('color_uz', models.CharField(max_length=100, null=True, verbose_name='Rang')),
                ('color_ru', models.CharField(max_length=100, null=True, verbose_name='Rang')),
                ('color_en', models.CharField(max_length=100, null=True, verbose_name='Rang')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('material_uz', models.CharField(max_length=100, null=True, verbose_name='Material')),
                ('material_ru', models.CharField(max_length=100, null=True, verbose_name='Material')),
                ('material_en', models.CharField(max_length=100, null=True, verbose_name='Material')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mashhur')),
                ('is_new', models.BooleanField(default=False, verbose_name='Yangi')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name="O'lcham")),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Qoldiq')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "O'lcham",
                'verbose_name_plural': "O'lchamlar",
                'unique_together': {('product', 'size')},
            },
        ),
    ]
