# Generated by Django 5.0.14 on 2026-01-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_path',
            field=models.CharField(blank=True, help_text='products/42/uuid.jpg', max_length=255, null=True, verbose_name='ImageKit path'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Rasm URL'),
        ),
    ]
