# Generated by Django 5.0.14 on 2026-01-03 10:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productimage_image_productimage_image_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size'], 'verbose_name': "O'lcham", 'verbose_name_plural': "O'lchamlar"},
        ),
        migrations.AlterField(
            model_name='product',
            name='color_hex',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='HEX rang #FFFFFF formatida bo‘lishi kerak', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Rang HEX kodi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Reyting'),
        ),
    ]
