# Generated by Django 5.2.7 on 2025-12-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
