# Generated by Django 5.2.7 on 2025-11-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Brand nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Brand nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Brand nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Brand nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brandlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
